-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."Departments"
(
    dept_no text NOT NULL,
    dept_name text NOT NULL,
    PRIMARY KEY (dept_no, dept_name)
);

CREATE TABLE public."Dept_Emp"
(
    emp_no integer NOT NULL,
    dept_no text NOT NULL,
    PRIMARY KEY (emp_no)
);

CREATE TABLE public."Dept_Manager"
(
    dept_no text NOT NULL,
    emp_no integer NOT NULL,
    PRIMARY KEY (emp_no)
);

CREATE TABLE public."Employees"
(
    employee_no integer NOT NULL,
    emp_title_id text,
    birth_date date,
    first_name text,
    last_name text,
    sex text,
    hire_date date,
    PRIMARY KEY (employee_no)
);

CREATE TABLE public."Salaries"
(
    emp_no integer NOT NULL,
    salary integer NOT NULL,
    PRIMARY KEY (emp_no)
);

CREATE TABLE public."Titles"
(
    "Title_ID" text NOT NULL,
    "Title" text,
    PRIMARY KEY ("Title_ID")
);

ALTER TABLE public."Titles"
    ADD FOREIGN KEY ("Title_ID")
    REFERENCES public."Employees" (emp_title_id)
    NOT VALID;


ALTER TABLE public."Departments"
    ADD FOREIGN KEY (dept_no)
    REFERENCES public."Dept_Emp" (dept_no)
    NOT VALID;


ALTER TABLE public."Dept_Manager"
    ADD FOREIGN KEY (dept_no)
    REFERENCES public."Departments" (dept_no)
    NOT VALID;

END;